security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_provider:
            entity:
                class: 'AppBundle:User'
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user_provider
            logout_on_user_change: true
            anonymous: ~
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: app_user_authentication_authenticate
                check_path: app_user_authentication_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   app_user_authentication_logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            user_checker: AppBundle\Security\UserChecker

    access_control:
    - { path: ^/user/authentication/authenticate/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/user/forgot_password/request_password/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/user/registration/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/user/forgot_password/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/card_type/, roles: ROLE_ADMIN }
    - { path: ^/killer_card/, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_USER }