app_user_authentication:
    prefix: /authentication/
    resource: 'authentication.yml'

app_user_blocking:
    prefix: /blocking/
    resource: 'blocking.yml'

app_user_deletion:
    prefix: /deletion/
    resource: 'deletion.yml'

app_user_edition:
    prefix: /edition/
    resource: 'edition.yml'

app_user_forgot_password:
    prefix: /forgot_password/
    resource: "forgot_password.yml"

app_user_listing:
    prefix: /listing/
    resource: "listing.yml"

app_user_registration:
    prefix: /registration/
    resource: 'registration.yml'