app_user_forgot_password_request:
    path: /request_password/
    defaults: { _controller: 'AppBundle:User\ForgotPassword:requestPassword' }
    options:
        titles:
            main: Requête de réinitialisation de mot de passe

app_user_forgot_password_reset:
    path: /reset/{id}/{tokenPassword}
    defaults: { _controller: 'AppBundle:User\ForgotPassword:reset' }
    options:
        titles:
            main: Réinitialisation de mot de passe