app_user_listing_list:
    path: /list/
    defaults: { _controller: 'AppBundle:User\Listing:listUser' }
    options:
        titles:
            main: Liste des utilisateurs
            sub: Résultat de la recherche
        breadcrumb:
            label: Liste utilisateurs
            icon: fa fa-user