app_player_killing_kill_player_by_game_master:
    path:   /kill_player_by_game_master/{id}
    defaults: { _controller: 'AppBundle:Player\Killer:killPlayerByGameMaster'}
    requirements:
        id: \d+
    options:
        titles:
            main: Tuer un joueur
        breadcrumb:
            icon: fas fa-skull-crossbones
            label: Tuer joueur
            parent: app_party_listing_list_party