AppBundle\Entity\Vote:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        trial:
            targetEntity: AppBundle\Entity\Trial
            inversedBy: votes
        owner:
            targetEntity: AppBundle\Entity\Player
        target:
            targetEntity: AppBundle\Entity\Player
    lifecycleCallbacks: {  }
