app_trial_creation_create_trial:
    path: /create_trial/{id}
    defaults: { _controller: 'AppBundle:Trial\Creation:createTrial' }
    requirements:
        id: \d+
    options:
        titles:
            main: Création d'un procès
        breadcrumb:
            icon: fa fa-plus
            label: Création procès
            parent: app_party_listing_list_party